powerCon <- read.table("../Data/household_power_consumption.txt", sep=";", skip = 66637, nrows = 2880, col.name=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
modDate <- strptime(paste(powerCon$Date, powerCon$Time), "%d/%m/%Y %H:%M:%S")
png("plot4.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "transparent")
par(mfcol = c(2,2))
plot(modDate,powerCon$Global_active_power, "l", xlab="",ylab="Global Active Power")
plot(modDate,powerCon$Sub_metering_1, "l",col="black",xlab="",ylab="Energy sub metering")
lines(modDate,powerCon$Sub_metering_2, "l", col="red")
lines(modDate,powerCon$Sub_metering_3, "l",col="blue")
legend("topright",lty=c(1),bty="n", col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(modDate,powerCon$Voltage,"l",xlab="DateTime",ylab="Voltage")
plot(modDate,powerCon$Global_reactive_power,"l",xlab="DateTime",ylab="Global_reactive_power")
dev.off()